apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
  namespace: gpu-jobs
spec:
  restartPolicy: OnFailure
  containers:
  - name: nvidia-smi
    # image: nvidia/cuda:latest
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    args:
    - "nvidia-smi"
    resources:
      limits:
        nvidia.com/gpu: 1
